### ISSUE TITLE
functionality to exclude bots from dataset

### ISSUE THREAD

**Issue by antter** [aicoe-aiops/github-labeler#13]
**Is your feature request related to a problem? Please describe.**
There are often bots that create issues or tag labels that we do not want to include in the dataset.

**Describe the solution you'd like**
A way to exclude certain users/bots from counting their issues or tags.

**Comment by goern** [comment]
Check wording please. 

@jzb @bproffitt could you give us some pointers? I think I remember one of you is on the 'word smiths' groups?!?

/kind feature
