### ISSUE TITLE
Label bot dataset [issue originally from mi repository]

### ISSUE THREAD

**Issue by xtuchyna** [aicoe-aiops/github-labeler#14]
We've had a issue in `mi` repository (https://github.com/thoth-station/mi/issues/278#issuecomment-865978612) for a longer period of time, related to labeling github issues (one of our back-then interns made some Transformer-based model, it is referenced in the issue).

Do you think the interest is the same and the issue can be moved (or closed and referenced) here?

**Comment by MichaelClifford** [comment]
@xtuchyna yes. This looks to me like an issue about the project we are working on here. It can be closed and referenced here : )
