### ISSUE TITLE
New minor release

### ISSUE THREAD

**Issue by antter** [aicoe-aiops/github-labeler#25]
Hey, Kebechet!

Create a new minor release, please.

(just want to see what happens)

**Comment by MichaelClifford** [comment]
@harshad16 how do we make @antter and myself a Maintainers?

**Comment by harshad16** [comment]
@MichaelClifford  you can add your github username to this list 
https://github.com/aicoe-aiops/github-labeler/blob/972445a841a748e7b467e50ce051715eb2b1c2c8/.thoth.yaml#L22
