### ISSUE TITLE
add JupyterBook to this repo

### ISSUE THREAD

**Issue by durandom** [aicoe-aiops/github-labeler#88]
use https://drive.google.com/file/d/1XsHRhRhQc3n1PnHNRTXL_5Qz5qRvf4eA/view as a basis.

- [x] convert presentation slides and notebooks into JupyterBook format
- [x] convert voiceover of video to text for book with HTTP://rev.ai
- [x] deploy JupyterBook via shower.meteor.zone

**Comment by antter** [comment]
https://shower.meteor.zone/order/meteor-rrbxl
